[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.black]
skip-string-normalization = true

[project]
name = 'formatters'
dynamic = ['version']
requires-python = '>=3.11'
dependencies = [
    'pandas',
    'openpyxl'
]
